### ISSUE TITLE
Singleton не выполняет свою главную обязанность

### ISSUE THREAD

**Issue by dzentota** [nixsolutions/design-patterns#1]
https://github.com/nixsolutions/design-patterns/blob/source/patterns/Creational/Singleton/SingletonTrait.php

волшебные методы должны быть приватными.

```php
$o = new Cashbox();
var_dump($o);
```
Выводит
`
class Cashbox#1 (1) {
  private $cash =>
  array(0) {
  }
}
`

**Comment by zyuzka** [comment]
@dzentota Спасибо. Исправил 2b7544b.
Ещё вариант отказаться от трейта и интрефейса, в пользу абстрактного класса.

P.S.
Из этого следует ещё один фикс 373cb55 для Multiton
